### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by K-C-Martin** [Biometris/isatabr#3]
Would it be possible to add an Open Source license to this repo? A permissive license would be ideal... it would be great to have the opportunity to repurpose some of your code (with your permission).

**Comment by BartJanvanRossum** [comment]
The repo already has a GLP-3 license, specified in the DESCRIPTION file. Does that work for you?

**Comment by K-C-Martin** [comment]
Ah great - apologies that I didn't see that, and thanks for the quick response.
